version: '3'
services:
  web:
    image: tiroserver:latest  # Usa la imagen 'tiroserver' que ya tienes
    ports:
      - "8080:80"
    volumes:
      - ./web;C:/var/www/html  # Usa el nombre de la carpeta "web;C"
    links:
      - db

  db:
    image: mariadb:latest
    environment:
      MYSQL_ROOT_PASSWORD: your-root-password
      MYSQL_DATABASE: your-database-name
    volumes:
      - ./db;C:/var/lib/mysql  # Usa el nombre de la carpeta "db;C"

